spring:
  application:
    name: BlogApp
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/blogappdb
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
auth:
  secret-key: 4e4ec0bb2dd33dfff9ac712f78eeb5650ae8aa69eff62f057faa2b72a4bed721
  issuer: BlogApp