INSERT INTO posts (id, title, text, version)
VALUES (1, 'Understanding REST APIs',
        'In this post, we explore the basics of REST APIs and how they are used in modern web applications.', 0),
       (2, 'Getting Started with Spring Boot',
        'Spring Boot simplifies Java development by providing a platform for rapid application development.', 0),
       (3, 'Top 10 Java Libraries You Should Know',
        'Discover the top Java libraries that can help improve your productivity and code quality.', 0),
       (4, 'Introduction to Microservices Architecture',
        'Learn about the microservices architecture and how it differs from the traditional monolithic approach.', 0),
       (5, 'Effective Debugging Techniques',
        'In this post, we discuss useful techniques for debugging Java applications more effectively.', 0),
       (6, 'Understanding Dependency Injection',
        'This article explains the concept of dependency injection and how it promotes loose coupling in code.', 0),
       (7, 'Best Practices for Writing Clean Code',
        'Learn the best practices for writing clean, readable, and maintainable Java code.', 0),
       (8, 'What is Object-Oriented Programming?',
        'This post provides an overview of object-oriented programming principles and their importance in Java.', 0),
       (9, 'Guide to Unit Testing with JUnit',
        'A comprehensive guide to writing effective unit tests using JUnit for Java applications.', 0),
       (10, 'Exploring Design Patterns in Java',
        'In this post, we take a deep dive into common design patterns and their implementations in Java.', 0);